package button;

public enum ButtonType {
	EQUAL, RESET, ZEROING, 
	OPEN_BRACKET, CLOSE_BRACKET, 
	DIVIDE, MULTIPLY, 
	ADD, SUBSTRACT, NUMERIC, 
	BACKSPACE, DOT,
	NEGATION, FACTORIAL,MODULO,
	TANGENS,EXP,COSINUS,PI,ONE_DIVIDE,
	LOGARITHM,SINUS,TEN_T0_X,SQRT,POWER;
}
