package button;

public enum ButtonType {
	EQUAL, 
	NUMERIC, RESET,BACKSPACE,ZEROING,NEGATION,FACTORIAL,MULTIPLY,DIVIDE,MODULO,TANGENS,EXP,COSINUS,PI
	,ONE_DIVIDE,LOGARITHM,SINUS,TEN_TO_X,SQRT,POWER,ADD,SUBSTRACT,OPEN_BRACKET,CLOSE_BRACKET,DOT;
}
